[Service]
Environment=RCLONE_MEDIA_VFS_CACHE_MODE=writes
ExecStart=
ExecStart=%h/hairglasses-studio/dotfiles/scripts/run-jellyfin-stack-rclone.sh %i /home/hg/jellyfin-stack/scripts/mount-gdrive-media.sh --env-file /home/hg/jellyfin-stack/.env --foreground --remote %i
ExecStop=
ExecStop=%h/hairglasses-studio/dotfiles/scripts/run-jellyfin-stack-rclone.sh %i /home/hg/jellyfin-stack/scripts/unmount-gdrive-media.sh --env-file /home/hg/jellyfin-stack/.env --remote %i
