// Package discordadmin provides Discord admin tools for hg-mcp.
package discordadmin

import (
	"fmt"

	"github.com/bwmarrin/discordgo"
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/hairglasses-studio/hg-mcp/internal/clients"
	"github.com/hairglasses-studio/hg-mcp/internal/mcp/tools"
)

// Module implements the ToolModule interface for Discord admin operations
type Module struct{}

func (m *Module) Name() string {
	return "discord_admin"
}

func (m *Module) Description() string {
	return "Discord server administration tools (channels, roles, members, moderation)"
}

func (m *Module) Tools() []tools.ToolDefinition {
	return []tools.ToolDefinition{
		// =======================================================================
		// Server Management Tools (5)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_create_channel",
				mcp.WithDescription("Create a new text or voice channel in the server."),
				mcp.WithString("name",
					mcp.Required(),
					mcp.Description("Channel name"),
				),
				mcp.WithString("type",
					mcp.Description("Channel type: 'text' (default), 'voice', 'news', 'forum'"),
				),
				mcp.WithString("category_id",
					mcp.Description("Parent category ID (optional)"),
				),
				mcp.WithString("topic",
					mcp.Description("Channel topic (text channels only)"),
				),
			),
			Handler:             handleCreateChannel,
			Category:            "discord",
			Subcategory:         "admin_channels",
			Tags:                []string{"discord", "admin", "channel", "create"},
			UseCases:            []string{"Create project channels", "Add voice rooms"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_delete_channel",
				mcp.WithDescription("Delete a channel from the server."),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the channel to delete"),
				),
			),
			Handler:             handleDeleteChannel,
			Category:            "discord",
			Subcategory:         "admin_channels",
			Tags:                []string{"discord", "admin", "channel", "delete"},
			UseCases:            []string{"Remove archived channels", "Cleanup"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_create_category",
				mcp.WithDescription("Create a new channel category."),
				mcp.WithString("name",
					mcp.Required(),
					mcp.Description("Category name"),
				),
				mcp.WithNumber("position",
					mcp.Description("Position in channel list (optional)"),
				),
			),
			Handler:             handleCreateCategory,
			Category:            "discord",
			Subcategory:         "admin_channels",
			Tags:                []string{"discord", "admin", "category", "create"},
			UseCases:            []string{"Organize channels by project", "Create team sections"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_edit_channel",
				mcp.WithDescription("Edit channel settings (name, topic, slowmode)."),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the channel to edit"),
				),
				mcp.WithString("name",
					mcp.Description("New channel name"),
				),
				mcp.WithString("topic",
					mcp.Description("New channel topic"),
				),
				mcp.WithNumber("slowmode",
					mcp.Description("Slowmode delay in seconds (0-21600)"),
				),
			),
			Handler:             handleEditChannel,
			Category:            "discord",
			Subcategory:         "admin_channels",
			Tags:                []string{"discord", "admin", "channel", "edit"},
			UseCases:            []string{"Update channel settings", "Set slowmode"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_lock_channel",
				mcp.WithDescription("Lock or unlock a channel (prevent/allow messages)."),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the channel to lock/unlock"),
				),
				mcp.WithBoolean("locked",
					mcp.Required(),
					mcp.Description("true to lock, false to unlock"),
				),
			),
			Handler:             handleLockChannel,
			Category:            "discord",
			Subcategory:         "admin_channels",
			Tags:                []string{"discord", "admin", "channel", "lock", "moderation"},
			UseCases:            []string{"Temporarily disable channel", "Prevent spam"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},

		// =======================================================================
		// Role Management Tools (6)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_create_role",
				mcp.WithDescription("Create a new role."),
				mcp.WithString("name",
					mcp.Required(),
					mcp.Description("Role name"),
				),
				mcp.WithString("color",
					mcp.Description("Role color in hex (e.g., '#FF0000' or '0xFF0000')"),
				),
				mcp.WithBoolean("hoist",
					mcp.Description("Display separately in member list (default: false)"),
				),
				mcp.WithBoolean("mentionable",
					mcp.Description("Allow @mentions of this role (default: false)"),
				),
			),
			Handler:             handleCreateRole,
			Category:            "discord",
			Subcategory:         "admin_roles",
			Tags:                []string{"discord", "admin", "role", "create"},
			UseCases:            []string{"Create team roles", "Add department tags"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_delete_role",
				mcp.WithDescription("Delete a role from the server."),
				mcp.WithString("role_id",
					mcp.Required(),
					mcp.Description("ID of the role to delete"),
				),
			),
			Handler:             handleDeleteRole,
			Category:            "discord",
			Subcategory:         "admin_roles",
			Tags:                []string{"discord", "admin", "role", "delete"},
			UseCases:            []string{"Remove obsolete roles", "Cleanup"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_assign_role",
				mcp.WithDescription("Assign a role to a member."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user"),
				),
				mcp.WithString("role_id",
					mcp.Required(),
					mcp.Description("ID of the role to assign"),
				),
			),
			Handler:             handleAssignRole,
			Category:            "discord",
			Subcategory:         "admin_roles",
			Tags:                []string{"discord", "admin", "role", "assign"},
			UseCases:            []string{"Grant access", "Add team member"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_revoke_role",
				mcp.WithDescription("Remove a role from a member."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user"),
				),
				mcp.WithString("role_id",
					mcp.Required(),
					mcp.Description("ID of the role to remove"),
				),
			),
			Handler:             handleRevokeRole,
			Category:            "discord",
			Subcategory:         "admin_roles",
			Tags:                []string{"discord", "admin", "role", "revoke"},
			UseCases:            []string{"Revoke access", "Remove from team"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_list_roles",
				mcp.WithDescription("List all roles in the server."),
			),
			Handler:             handleListRoles,
			Category:            "discord",
			Subcategory:         "admin_roles",
			Tags:                []string{"discord", "admin", "role", "list"},
			UseCases:            []string{"View role hierarchy", "Find role IDs"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_edit_role",
				mcp.WithDescription("Edit an existing role."),
				mcp.WithString("role_id",
					mcp.Required(),
					mcp.Description("ID of the role to edit"),
				),
				mcp.WithString("name",
					mcp.Description("New role name"),
				),
				mcp.WithString("color",
					mcp.Description("New role color in hex"),
				),
			),
			Handler:             handleEditRole,
			Category:            "discord",
			Subcategory:         "admin_roles",
			Tags:                []string{"discord", "admin", "role", "edit"},
			UseCases:            []string{"Update role settings", "Change color"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},

		// =======================================================================
		// Member Management Tools (7)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_member_info",
				mcp.WithDescription("Get detailed information about a member."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user"),
				),
			),
			Handler:             handleMemberInfo,
			Category:            "discord",
			Subcategory:         "admin_members",
			Tags:                []string{"discord", "admin", "member", "info"},
			UseCases:            []string{"Check user details", "View roles"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_list_members",
				mcp.WithDescription("List members in the server."),
				mcp.WithNumber("limit",
					mcp.Description("Maximum members to return (default: 100, max: 1000)"),
				),
			),
			Handler:             handleListMembers,
			Category:            "discord",
			Subcategory:         "admin_members",
			Tags:                []string{"discord", "admin", "member", "list"},
			UseCases:            []string{"Browse members", "Audit server"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_kick",
				mcp.WithDescription("Kick a member from the server."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user to kick"),
				),
				mcp.WithString("reason",
					mcp.Description("Reason for the kick (logged in audit)"),
				),
			),
			Handler:             handleKick,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "kick", "moderation"},
			UseCases:            []string{"Remove rule violators", "Enforce policies"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_ban",
				mcp.WithDescription("Ban a member from the server."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user to ban"),
				),
				mcp.WithString("reason",
					mcp.Description("Reason for the ban (logged in audit)"),
				),
				mcp.WithNumber("delete_days",
					mcp.Description("Days of messages to delete (0-7, default: 0)"),
				),
			),
			Handler:             handleBan,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "ban", "moderation"},
			UseCases:            []string{"Permanently remove users", "Block bad actors"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_unban",
				mcp.WithDescription("Remove a ban from a user."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user to unban"),
				),
			),
			Handler:             handleUnban,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "unban", "moderation"},
			UseCases:            []string{"Restore access", "Second chance"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_timeout",
				mcp.WithDescription("Timeout a member (temporary mute)."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user to timeout"),
				),
				mcp.WithNumber("duration_minutes",
					mcp.Required(),
					mcp.Description("Timeout duration in minutes (max: 40320 = 28 days)"),
				),
				mcp.WithString("reason",
					mcp.Description("Reason for the timeout"),
				),
			),
			Handler:             handleTimeout,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "timeout", "mute", "moderation"},
			UseCases:            []string{"Temporary silence", "Cool down period"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_set_nickname",
				mcp.WithDescription("Set a member's nickname."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user"),
				),
				mcp.WithString("nickname",
					mcp.Required(),
					mcp.Description("New nickname (empty string to clear)"),
				),
			),
			Handler:             handleSetNickname,
			Category:            "discord",
			Subcategory:         "admin_members",
			Tags:                []string{"discord", "admin", "nickname", "member"},
			UseCases:            []string{"Enforce naming conventions", "Set display names"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},

		// =======================================================================
		// Voice Management Tools (5)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_voice_status",
				mcp.WithDescription("Get status of all voice channels (who is where)."),
			),
			Handler:             handleVoiceStatus,
			Category:            "discord",
			Subcategory:         "admin_voice",
			Tags:                []string{"discord", "admin", "voice", "status"},
			UseCases:            []string{"See who is in voice", "Monitor activity"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_voice_move",
				mcp.WithDescription("Move a member to a different voice channel."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user to move"),
				),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the destination voice channel"),
				),
			),
			Handler:             handleVoiceMove,
			Category:            "discord",
			Subcategory:         "admin_voice",
			Tags:                []string{"discord", "admin", "voice", "move"},
			UseCases:            []string{"Redirect to meeting room", "Organize teams"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_voice_disconnect",
				mcp.WithDescription("Disconnect a member from voice."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user to disconnect"),
				),
			),
			Handler:             handleVoiceDisconnect,
			Category:            "discord",
			Subcategory:         "admin_voice",
			Tags:                []string{"discord", "admin", "voice", "disconnect"},
			UseCases:            []string{"Clear idle users", "End sessions"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_voice_mute",
				mcp.WithDescription("Server mute/unmute a member in voice."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user"),
				),
				mcp.WithBoolean("muted",
					mcp.Required(),
					mcp.Description("true to mute, false to unmute"),
				),
			),
			Handler:             handleVoiceMute,
			Category:            "discord",
			Subcategory:         "admin_voice",
			Tags:                []string{"discord", "admin", "voice", "mute"},
			UseCases:            []string{"Enforce silence during recording", "Mute during presentations"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_voice_deafen",
				mcp.WithDescription("Server deafen/undeafen a member in voice."),
				mcp.WithString("user_id",
					mcp.Required(),
					mcp.Description("ID of the user"),
				),
				mcp.WithBoolean("deafened",
					mcp.Required(),
					mcp.Description("true to deafen, false to undeafen"),
				),
			),
			Handler:             handleVoiceDeafen,
			Category:            "discord",
			Subcategory:         "admin_voice",
			Tags:                []string{"discord", "admin", "voice", "deafen"},
			UseCases:            []string{"Full audio isolation", "Private discussions"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},

		// =======================================================================
		// Moderation Tools (5)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_purge",
				mcp.WithDescription("Bulk delete messages from a channel (2-100 messages, max 14 days old)."),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the channel"),
				),
				mcp.WithNumber("count",
					mcp.Required(),
					mcp.Description("Number of messages to delete (2-100)"),
				),
			),
			Handler:             handlePurge,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "purge", "delete", "moderation"},
			UseCases:            []string{"Clean up spam", "Remove off-topic messages"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_pin",
				mcp.WithDescription("Pin or unpin a message."),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the channel"),
				),
				mcp.WithString("message_id",
					mcp.Required(),
					mcp.Description("ID of the message"),
				),
				mcp.WithBoolean("pinned",
					mcp.Required(),
					mcp.Description("true to pin, false to unpin"),
				),
			),
			Handler:             handlePin,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "pin", "message"},
			UseCases:            []string{"Highlight important messages", "Save announcements"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_audit_log",
				mcp.WithDescription("Get the server audit log."),
				mcp.WithNumber("limit",
					mcp.Description("Number of entries to retrieve (default: 50, max: 100)"),
				),
				mcp.WithString("user_id",
					mcp.Description("Filter by user who performed the action"),
				),
				mcp.WithNumber("action_type",
					mcp.Description("Filter by action type (see Discord docs for codes)"),
				),
			),
			Handler:             handleAuditLog,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "audit", "log", "security"},
			UseCases:            []string{"Track changes", "Investigate incidents"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_slowmode",
				mcp.WithDescription("Set slowmode delay for a channel."),
				mcp.WithString("channel_id",
					mcp.Required(),
					mcp.Description("ID of the channel"),
				),
				mcp.WithNumber("seconds",
					mcp.Required(),
					mcp.Description("Slowmode delay in seconds (0 to disable, max: 21600)"),
				),
			),
			Handler:             handleSlowmode,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "slowmode", "moderation"},
			UseCases:            []string{"Rate limit discussions", "Prevent spam"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_list_bans",
				mcp.WithDescription("List banned users."),
				mcp.WithNumber("limit",
					mcp.Description("Maximum bans to return (default: 100)"),
				),
			),
			Handler:             handleListBans,
			Category:            "discord",
			Subcategory:         "admin_moderation",
			Tags:                []string{"discord", "admin", "ban", "list"},
			UseCases:            []string{"Review bans", "Audit moderation"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},

		// =======================================================================
		// Scheduled Events (4)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_create_event",
				mcp.WithDescription("Create a scheduled event."),
				mcp.WithString("name",
					mcp.Required(),
					mcp.Description("Event name"),
				),
				mcp.WithString("description",
					mcp.Description("Event description"),
				),
				mcp.WithString("start_time",
					mcp.Required(),
					mcp.Description("Start time in RFC3339 format (e.g., 2024-01-15T14:00:00Z)"),
				),
				mcp.WithString("end_time",
					mcp.Description("End time in RFC3339 format (required for external events)"),
				),
				mcp.WithString("location",
					mcp.Description("External location (makes this an external event)"),
				),
				mcp.WithString("channel_id",
					mcp.Description("Voice/Stage channel ID (for voice events)"),
				),
			),
			Handler:             handleCreateEvent,
			Category:            "discord",
			Subcategory:         "admin_events",
			Tags:                []string{"discord", "admin", "event", "schedule"},
			UseCases:            []string{"Schedule jam sessions", "Plan meetings"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_update_event",
				mcp.WithDescription("Update an existing scheduled event."),
				mcp.WithString("event_id",
					mcp.Required(),
					mcp.Description("ID of the event to update"),
				),
				mcp.WithString("name",
					mcp.Description("New event name"),
				),
				mcp.WithString("description",
					mcp.Description("New event description"),
				),
				mcp.WithString("start_time",
					mcp.Description("New start time in RFC3339 format"),
				),
			),
			Handler:             handleUpdateEvent,
			Category:            "discord",
			Subcategory:         "admin_events",
			Tags:                []string{"discord", "admin", "event", "update"},
			UseCases:            []string{"Reschedule events", "Update details"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_delete_event",
				mcp.WithDescription("Delete a scheduled event."),
				mcp.WithString("event_id",
					mcp.Required(),
					mcp.Description("ID of the event to delete"),
				),
			),
			Handler:             handleDeleteEvent,
			Category:            "discord",
			Subcategory:         "admin_events",
			Tags:                []string{"discord", "admin", "event", "delete"},
			UseCases:            []string{"Cancel events", "Remove old events"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_list_events",
				mcp.WithDescription("List scheduled events."),
			),
			Handler:             handleListEvents,
			Category:            "discord",
			Subcategory:         "admin_events",
			Tags:                []string{"discord", "admin", "event", "list"},
			UseCases:            []string{"View upcoming events", "Check schedule"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},

		// =======================================================================
		// Interactive Components (3)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_send_buttons",
				mcp.WithDescription("Send a message with action buttons."),
				mcp.WithString("channel_id",
					mcp.Description("Channel to send to (uses default if not specified)"),
				),
				mcp.WithString("content",
					mcp.Required(),
					mcp.Description("Message content"),
				),
				mcp.WithString("buttons",
					mcp.Required(),
					mcp.Description("JSON array of buttons: [{\"label\": \"...\", \"custom_id\": \"...\", \"style\": \"primary|secondary|success|danger\"}]"),
				),
			),
			Handler:             handleSendButtons,
			Category:            "discord",
			Subcategory:         "admin_components",
			Tags:                []string{"discord", "admin", "buttons", "interactive"},
			UseCases:            []string{"Approval workflows", "Quick actions"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_discord_admin_send_select",
				mcp.WithDescription("Send a message with a select menu."),
				mcp.WithString("channel_id",
					mcp.Description("Channel to send to (uses default if not specified)"),
				),
				mcp.WithString("content",
					mcp.Required(),
					mcp.Description("Message content"),
				),
				mcp.WithString("placeholder",
					mcp.Description("Placeholder text for the select menu"),
				),
				mcp.WithString("custom_id",
					mcp.Required(),
					mcp.Description("Custom ID for the select menu"),
				),
				mcp.WithString("options",
					mcp.Required(),
					mcp.Description("JSON array of options: [{\"label\": \"...\", \"value\": \"...\", \"description\": \"...\"}]"),
				),
			),
			Handler:             handleSendSelect,
			Category:            "discord",
			Subcategory:         "admin_components",
			Tags:                []string{"discord", "admin", "select", "dropdown", "interactive"},
			UseCases:            []string{"Multi-choice forms", "Selection menus"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "discord_admin",
			IsWrite:             true,
		},

		// =======================================================================
		// Guild/Server Info (1)
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_discord_admin_server_info",
				mcp.WithDescription("Get detailed server information."),
			),
			Handler:             handleServerInfo,
			Category:            "discord",
			Subcategory:         "admin_server",
			Tags:                []string{"discord", "admin", "server", "info"},
			UseCases:            []string{"Audit server settings", "Check server stats"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "discord_admin",
		},
	}
}

var getClient = tools.LazyClient(clients.NewDiscordClient)

// parseColor parses a color string (hex) to int
func parseColor(colorStr string) int {
	if colorStr == "" {
		return 0x5865F2 // Discord blurple default
	}
	var color int
	if _, err := fmt.Sscanf(colorStr, "#%x", &color); err == nil {
		return color
	}
	if _, err := fmt.Sscanf(colorStr, "0x%x", &color); err == nil {
		return color
	}
	return 0x5865F2
}

// channelTypeFromString converts string to Discord channel type
func channelTypeFromString(t string) discordgo.ChannelType {
	switch t {
	case "voice":
		return discordgo.ChannelTypeGuildVoice
	case "news":
		return discordgo.ChannelTypeGuildNews
	case "forum":
		return discordgo.ChannelTypeGuildForum
	case "stage":
		return discordgo.ChannelTypeGuildStageVoice
	default:
		return discordgo.ChannelTypeGuildText
	}
}

// buttonStyleFromString converts string to Discord button style
func buttonStyleFromString(s string) discordgo.ButtonStyle {
	switch s {
	case "secondary":
		return discordgo.SecondaryButton
	case "success":
		return discordgo.SuccessButton
	case "danger":
		return discordgo.DangerButton
	case "link":
		return discordgo.LinkButton
	default:
		return discordgo.PrimaryButton
	}
}

// init registers this module with the global registry
func init() {
	tools.GetRegistry().RegisterModule(&Module{})
}
