// Package gdrive provides Google Drive MCP tools for hg-mcp.
package gdrive

import (
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/hairglasses-studio/hg-mcp/internal/mcp/tools"
)

// Module implements the ToolModule interface for Google Drive operations
type Module struct{}

func (m *Module) Name() string {
	return "gdrive"
}

func (m *Module) Description() string {
	return "Google Drive tools for managing VJ clips and media files"
}

func (m *Module) Tools() []tools.ToolDefinition {
	return []tools.ToolDefinition{
		// =======================================================================
		// LISTING & NAVIGATION
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_gdrive_list",
				mcp.WithDescription("List files and folders in a Google Drive directory. Returns file names, sizes, and IDs for further operations."),
				mcp.WithString("folder_id",
					mcp.Description("Folder ID to list (use 'root' for My Drive root, or paste folder ID from URL)"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum number of files to return (default: 100)"),
				),
				mcp.WithString("page_token",
					mcp.Description("Page token for pagination (from previous response)"),
				),
			),
			Handler:             handleList,
			Category:            "gdrive",
			Subcategory:         "navigation",
			Tags:                []string{"gdrive", "list", "files", "folders"},
			UseCases:            []string{"Browse VJ clip folders", "Find media files"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_search",
				mcp.WithDescription("Search for files in Google Drive by name, type, or folder. Great for finding VJ clips by name."),
				mcp.WithString("query",
					mcp.Description("Search query (file name contains this text)"),
				),
				mcp.WithString("file_type",
					mcp.Description("Filter by type: 'video', 'image', 'audio', 'folder', or leave empty for all"),
				),
				mcp.WithString("folder_id",
					mcp.Description("Limit search to specific folder ID"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum results (default: 50)"),
				),
			),
			Handler:             handleSearch,
			Category:            "gdrive",
			Subcategory:         "navigation",
			Tags:                []string{"gdrive", "search", "find", "video", "clips"},
			UseCases:            []string{"Find VJ clips by name", "Search for video files"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_info",
				mcp.WithDescription("Get detailed information about a file or folder including size, dates, and path."),
				mcp.WithString("file_id",
					mcp.Required(),
					mcp.Description("File or folder ID"),
				),
				mcp.WithBoolean("include_path",
					mcp.Description("Include full folder path (slightly slower)"),
				),
			),
			Handler:             handleInfo,
			Category:            "gdrive",
			Subcategory:         "navigation",
			Tags:                []string{"gdrive", "info", "metadata"},
			UseCases:            []string{"Check file details", "Verify file before download"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_shared_drives",
				mcp.WithDescription("List available shared drives (team drives) that you have access to."),
			),
			Handler:             handleSharedDrives,
			Category:            "gdrive",
			Subcategory:         "navigation",
			Tags:                []string{"gdrive", "shared", "team", "drives"},
			UseCases:            []string{"Find shared VJ clip libraries", "Access team drives"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},

		// =======================================================================
		// DOWNLOADING
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_gdrive_download",
				mcp.WithDescription("Download a single file from Google Drive to local storage."),
				mcp.WithString("file_id",
					mcp.Required(),
					mcp.Description("File ID to download"),
				),
				mcp.WithString("destination",
					mcp.Description("Local destination path (directory or full path). Defaults to current directory."),
				),
			),
			Handler:             handleDownload,
			Category:            "gdrive",
			Subcategory:         "download",
			Tags:                []string{"gdrive", "download", "file"},
			UseCases:            []string{"Download VJ clip", "Get single media file"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "gdrive",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_download_folder",
				mcp.WithDescription("Download all files from a Google Drive folder. Can filter by type (video/image) for VJ clips."),
				mcp.WithString("folder_id",
					mcp.Required(),
					mcp.Description("Folder ID to download"),
				),
				mcp.WithString("destination",
					mcp.Required(),
					mcp.Description("Local destination directory"),
				),
				mcp.WithString("file_type",
					mcp.Description("Filter: 'video' for VJ clips, 'image' for stills, or empty for all files"),
				),
				mcp.WithBoolean("recursive",
					mcp.Description("Include subfolders (default: false)"),
				),
			),
			Handler:             handleDownloadFolder,
			Category:            "gdrive",
			Subcategory:         "download",
			Tags:                []string{"gdrive", "download", "folder", "batch", "vj", "clips"},
			UseCases:            []string{"Download VJ clip folder for show", "Batch download media"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "gdrive",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_download_videos",
				mcp.WithDescription("Quick download of all video files from a folder - optimized for VJ clip preparation."),
				mcp.WithString("folder_id",
					mcp.Required(),
					mcp.Description("Folder ID containing VJ clips"),
				),
				mcp.WithString("destination",
					mcp.Required(),
					mcp.Description("Local destination directory (e.g., ~/VJ/Sets/Tonight)"),
				),
				mcp.WithBoolean("recursive",
					mcp.Description("Include videos from subfolders"),
				),
			),
			Handler:             handleDownloadVideos,
			Category:            "gdrive",
			Subcategory:         "download",
			Tags:                []string{"gdrive", "download", "video", "vj", "clips", "batch"},
			UseCases:            []string{"Prepare VJ clips for tonight's show", "Batch download video files"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "gdrive",
			IsWrite:             true,
		},

		// =======================================================================
		// STORAGE & QUOTA
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_gdrive_quota",
				mcp.WithDescription("Check Google Drive storage quota and available space."),
			),
			Handler:             handleQuota,
			Category:            "gdrive",
			Subcategory:         "storage",
			Tags:                []string{"gdrive", "quota", "storage", "space"},
			UseCases:            []string{"Check available storage", "Monitor drive usage"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},

		// =======================================================================
		// VJ WORKFLOW
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_gdrive_vj_sync",
				mcp.WithDescription("Sync VJ clips from a Google Drive folder to local Resolume media folder. Only downloads new/changed files."),
				mcp.WithString("source_folder_id",
					mcp.Required(),
					mcp.Description("Google Drive folder ID containing VJ clips"),
				),
				mcp.WithString("destination",
					mcp.Description("Local Resolume media folder (defaults to ~/Documents/Resolume Arena/Media)"),
				),
				mcp.WithBoolean("recursive",
					mcp.Description("Include subfolders"),
				),
			),
			Handler:             handleVJSync,
			Category:            "gdrive",
			Subcategory:         "vj",
			Tags:                []string{"gdrive", "vj", "sync", "resolume", "clips"},
			UseCases:            []string{"Sync VJ library before show", "Update Resolume clips"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "gdrive",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_vj_packs",
				mcp.WithDescription("List available VJ clip packs that can be synced with rclone. Shows pack names and folder mappings."),
			),
			Handler:             handleVJPacks,
			Category:            "gdrive",
			Subcategory:         "vj",
			Tags:                []string{"gdrive", "vj", "packs", "list", "catalog"},
			UseCases:            []string{"Browse available VJ packs", "Choose packs for tonight's show"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_rclone_sync",
				mcp.WithDescription("Fast sync of VJ packs using rclone. Much faster than API for large files. Supports syncing specific packs or all packs."),
				mcp.WithString("pack",
					mcp.Required(),
					mcp.Description("Pack name(s) to sync: 'hackerglasses', 'hairglasses,fetz,masks', or 'all'"),
				),
				mcp.WithString("destination",
					mcp.Description("Destination folder (defaults to ~/Documents/Resolume Arena/Media)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview sync without transferring files"),
				),
			),
			Handler:             handleRcloneSync,
			Category:            "gdrive",
			Subcategory:         "vj",
			Tags:                []string{"gdrive", "vj", "sync", "rclone", "fast", "packs"},
			UseCases:            []string{"Fast sync VJ packs for show", "Update clip library with rclone"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "gdrive",
			IsWrite:             true,
		},

		// =======================================================================
		// VJ ZIP PACKS
		// =======================================================================
		{
			Tool: mcp.NewTool("aftrs_gdrive_vj_zip_packs",
				mcp.WithDescription("List available VJ clip zip pack archives. Shows downloadable zip files containing VJ loops and visuals."),
			),
			Handler:             handleVJZipPacks,
			Category:            "gdrive",
			Subcategory:         "vj_zip",
			Tags:                []string{"gdrive", "vj", "zip", "packs", "catalog"},
			UseCases:            []string{"Browse VJ zip archives", "Find downloadable clip packs"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_vj_zip_search",
				mcp.WithDescription("Search VJ clip zip packs by name, description, or tags."),
				mcp.WithString("query",
					mcp.Required(),
					mcp.Description("Search query (e.g., 'beeple', 'loops', '3d')"),
				),
			),
			Handler:             handleVJZipSearch,
			Category:            "gdrive",
			Subcategory:         "vj_zip",
			Tags:                []string{"gdrive", "vj", "zip", "search"},
			UseCases:            []string{"Find specific VJ packs", "Search by style or artist"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "gdrive",
		},
		{
			Tool: mcp.NewTool("aftrs_gdrive_vj_zip_download",
				mcp.WithDescription("Download and extract a VJ clip zip pack. Uses rclone for fast downloads and unzip for extraction."),
				mcp.WithString("key",
					mcp.Required(),
					mcp.Description("Pack key from catalog (e.g., 'supreme_cyphers_v3', 'beeple_brainfeeder')"),
				),
				mcp.WithString("destination",
					mcp.Description("Destination folder (defaults to ~/Documents/Resolume Arena/Media)"),
				),
				mcp.WithBoolean("extract",
					mcp.Description("Extract zip after download (default: true)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview download without transferring files"),
				),
			),
			Handler:             handleVJZipDownload,
			Category:            "gdrive",
			Subcategory:         "vj_zip",
			Tags:                []string{"gdrive", "vj", "zip", "download", "extract"},
			UseCases:            []string{"Download VJ clip pack", "Install new visuals for show"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "gdrive",
			IsWrite:             true,
		},
	}
}

// init registers this module with the global registry
func init() {
	tools.GetRegistry().RegisterModule(&Module{})
}
