# Input devices, system utilities, misc
[arch]
packages = [
    # Input devices
    { name = "python-pyqt6" },
    { name = "qt6-svg" },
    { name = "python-gobject" },
    { name = "python-cairo" },
    { name = "python-cryptography" },
    { name = "gtk4" },
    { name = "libadwaita" },
    { name = "gtk4-layer-shell" },
    { name = "hidapi" },
    { name = "libevdev" },
    { name = "makima-bin" },
    { name = "openlinkhub-bin", hooks = { after_sync = ["sudo", "systemctl", "enable", "--now", "openlinkhub.service"] } },
    { name = "udev-usb-sync" },

    # Bluetooth
    { name = "blueman" },
    { name = "bluez" },
    { name = "bluez-utils" },

    # Hardware control
    { name = "liquidctl" },

    # System tools
    { name = "inotify-tools" },
    { name = "wtfutil" },
    { name = "bagels" },
    { name = "b43-fwcutter" },
    { name = "xorg-xrdb" },

    # AUR helper
    { name = "yay" },
    { name = "paru" },
    { name = "metapac" },
]
