#? Config file for btop — Snazzy rice

color_theme = "snazzy"
theme_background = False

truecolor = True
force_tty = False
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_gradient = True
proc_per_core = False
proc_filter_kernel = False
cpu_graph_upper = "total"
cpu_graph_lower = "total"
cpu_sensor = "Auto"
show_coretemp = True
temp_scale = "celsius"
show_cpu_freq = True
clock_format = "%H:%M"
background_update = True
mem_graphs = True
mem_below_net = False
swap_disk = True
show_disks = True
show_io_stat = True
net_download = 100
net_upload = 100
net_auto = True
net_sync = True
net_iface = ""
show_battery = True
log_level = "WARNING"
