#!/usr/bin/env bats
# Tests for scripts/hg-gitignore.sh — .gitignore template assembler

load 'test_helper'

setup() {
    export BATS_TEST_TMPDIR="$(mktemp -d)"

    # Build synthetic git template dir
    export TEST_GIT_DIR="${BATS_TEST_TMPDIR}/git"
    mkdir -p "$TEST_GIT_DIR"

    cat > "${TEST_GIT_DIR}/gitignore-base" << 'EOF'
.env
.DS_Store
*.log
EOF

    cat > "${TEST_GIT_DIR}/gitignore-go" << 'EOF'
/bin/
*.exe
vendor/
EOF

    cat > "${TEST_GIT_DIR}/gitignore-node" << 'EOF'
node_modules/
dist/
.next/
EOF

    cat > "${TEST_GIT_DIR}/gitignore-python" << 'EOF'
__pycache__/
*.pyc
.venv/
EOF

    GITIGNORE_SH="${DOTFILES_DIR}/scripts/hg-gitignore.sh"
}

teardown() {
    [[ -d "${BATS_TEST_TMPDIR}" ]] && rm -rf "${BATS_TEST_TMPDIR}"
}

# Helper: run hg-gitignore with our test template dir
run_gitignore() {
    run bash -c "
        sed 's|GIT_DIR=.*|GIT_DIR=\"${TEST_GIT_DIR}\"|' '${GITIGNORE_SH}' \
            > '${BATS_TEST_TMPDIR}/hg-gitignore-patched.sh'
        chmod +x '${BATS_TEST_TMPDIR}/hg-gitignore-patched.sh'
        cd '${BATS_TEST_TMPDIR}'
        bash '${BATS_TEST_TMPDIR}/hg-gitignore-patched.sh' $*
    "
}

# --- Explicit language argument ---

@test "hg-gitignore: go produces base + go patterns" {
    run_gitignore go
    assert_success
    assert_output --partial ".env"
    assert_output --partial ".DS_Store"
    assert_output --partial "/bin/"
    assert_output --partial "vendor/"
}

@test "hg-gitignore: node produces base + node patterns" {
    run_gitignore node
    assert_success
    assert_output --partial ".env"
    assert_output --partial "node_modules/"
    assert_output --partial "dist/"
}

@test "hg-gitignore: python produces base + python patterns" {
    run_gitignore python
    assert_success
    assert_output --partial ".env"
    assert_output --partial "__pycache__/"
    assert_output --partial "*.pyc"
}

@test "hg-gitignore: hybrid produces base + go + node patterns" {
    run_gitignore hybrid
    assert_success
    assert_output --partial ".env"
    assert_output --partial "/bin/"
    assert_output --partial "node_modules/"
}

@test "hg-gitignore: go output does NOT include node patterns" {
    run_gitignore go
    assert_success
    refute_output --partial "node_modules/"
    refute_output --partial "__pycache__/"
}

@test "hg-gitignore: node output does NOT include go patterns" {
    run_gitignore node
    assert_success
    refute_output --partial "/bin/"
    refute_output --partial "vendor/"
}

# --- Header and footer ---

@test "hg-gitignore: output starts with generated-by comment" {
    run_gitignore go
    assert_success
    assert_line --index 0 --partial "Generated by hg-gitignore.sh"
}

@test "hg-gitignore: output ends with project-specific section marker" {
    run_gitignore go
    assert_success
    assert_output --partial "Project-specific"
}

# --- Unknown language ---

@test "hg-gitignore: unknown language exits with error" {
    run_gitignore rust
    assert_failure
    assert_output --partial "Unknown language: rust"
}

# --- Auto-detection ---

@test "hg-gitignore: auto-detects go from go.mod" {
    touch "${BATS_TEST_TMPDIR}/go.mod"
    run_gitignore
    assert_success
    assert_output --partial "/bin/"
    assert_output --partial "vendor/"
}

@test "hg-gitignore: auto-detects node from package.json" {
    touch "${BATS_TEST_TMPDIR}/package.json"
    run_gitignore
    assert_success
    assert_output --partial "node_modules/"
}

@test "hg-gitignore: auto-detects python from pyproject.toml" {
    touch "${BATS_TEST_TMPDIR}/pyproject.toml"
    run_gitignore
    assert_success
    assert_output --partial "__pycache__/"
}

@test "hg-gitignore: auto-detects hybrid from go.mod + package.json" {
    touch "${BATS_TEST_TMPDIR}/go.mod"
    touch "${BATS_TEST_TMPDIR}/package.json"
    run_gitignore
    assert_success
    assert_output --partial "/bin/"
    assert_output --partial "node_modules/"
}

@test "hg-gitignore: no language and no marker files exits with error" {
    run_gitignore
    assert_failure
    assert_output --partial "Usage"
}
