[General]
CurrentTheme = snazzy
IconSize = 25
Layer = top
Exclusive = false
SmartView = true
Position = bottom
AutoHideDelay = 250
SystemGapUsed = true
Margin = 8
ContextPos = 8

[General.preview]
Mode = static
FPS = 30
BufferSize = 5
ShowDelay = 350
HideDelay = 220
MoveDelay = 90
