// Package pages provides MCP tools for managing structured notes/pages in Notion.
package pages

import (
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/hairglasses-studio/hg-mcp/internal/mcp/tools"
)

// Module implements the ToolModule interface for pages tools
type Module struct{}

func (m *Module) Name() string {
	return "pages"
}

func (m *Module) Description() string {
	return "Structured notes and pages management backed by Notion with tagging, categories, and templates"
}

func (m *Module) Tools() []tools.ToolDefinition {
	return []tools.ToolDefinition{
		// --- CRUD ---
		{
			Tool: mcp.NewTool("hg_pages_list",
				mcp.WithDescription("List pages from the notes database. Excludes templates. Sorted by last edited time descending."),
				mcp.WithString("category",
					mcp.Description("Filter by category (e.g., Notes, Documentation, Journal)"),
				),
				mcp.WithString("tag",
					mcp.Description("Filter by tag"),
				),
				mcp.WithString("status",
					mcp.Description("Filter by status (Draft, Active, Archived)"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum pages to return (default: 25, max: 100)"),
				),
				mcp.WithString("cursor",
					mcp.Description("Pagination cursor from a previous list result"),
				),
			),
			Handler:             handleList,
			Category:            "pages",
			Subcategory:         "crud",
			Tags:                []string{"pages", "list", "notes", "notion"},
			UseCases:            []string{"Browse notes", "Filter pages by category or tag"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
		},
		{
			Tool: mcp.NewTool("hg_pages_read",
				mcp.WithDescription("Read a page's properties and optionally its content blocks."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID"),
				),
				mcp.WithBoolean("content",
					mcp.Description("Include page content blocks (default: false)"),
				),
				mcp.WithString("format",
					mcp.Description("Output format: 'json' (default) or 'markdown'"),
				),
			),
			Handler:             handleRead,
			Category:            "pages",
			Subcategory:         "crud",
			Tags:                []string{"pages", "read", "get", "notion"},
			UseCases:            []string{"Read a note", "Get page content as markdown"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
		},
		{
			Tool: mcp.NewTool("hg_pages_write",
				mcp.WithDescription("Create a new page in the notes database with title, content, tags, category, and status."),
				mcp.WithString("title",
					mcp.Required(),
					mcp.Description("Page title"),
				),
				mcp.WithString("content",
					mcp.Description("Page content (added as a paragraph block)"),
				),
				mcp.WithString("tags",
					mcp.Description("Comma-separated tags (e.g., 'project,idea,music')"),
				),
				mcp.WithString("category",
					mcp.Description("Page category (e.g., Notes, Documentation, Journal)"),
				),
				mcp.WithString("status",
					mcp.Description("Page status (Draft, Active, Archived). Default: Draft"),
				),
			),
			Handler:             handleWrite,
			Category:            "pages",
			Subcategory:         "crud",
			Tags:                []string{"pages", "write", "create", "notion"},
			UseCases:            []string{"Create a new note", "Write a document"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("hg_pages_update",
				mcp.WithDescription("Append content blocks to an existing page."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID"),
				),
				mcp.WithString("content",
					mcp.Required(),
					mcp.Description("Content to append"),
				),
				mcp.WithString("block_type",
					mcp.Description("Block type: 'paragraph' (default), 'heading_1', 'heading_2', 'heading_3', 'bulleted_list_item', 'numbered_list_item', 'to_do', 'quote', 'code'"),
				),
			),
			Handler:             handleUpdate,
			Category:            "pages",
			Subcategory:         "crud",
			Tags:                []string{"pages", "update", "append", "notion"},
			UseCases:            []string{"Add content to a note", "Append to a document"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("hg_pages_search",
				mcp.WithDescription("Search pages by title within the notes database. Results are scoped to this database and exclude templates."),
				mcp.WithString("query",
					mcp.Required(),
					mcp.Description("Title text to search for"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum results (default: 10, max: 50)"),
				),
			),
			Handler:             handleSearch,
			Category:            "pages",
			Subcategory:         "crud",
			Tags:                []string{"pages", "search", "find", "notion"},
			UseCases:            []string{"Find a note by title", "Search notes"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
		},
		{
			Tool: mcp.NewTool("hg_pages_delete",
				mcp.WithDescription("Archive (soft-delete) a page."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID to archive"),
				),
			),
			Handler:             handleDelete,
			Category:            "pages",
			Subcategory:         "crud",
			Tags:                []string{"pages", "delete", "archive", "notion"},
			UseCases:            []string{"Archive a note", "Remove a page"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},

		// --- Organization ---
		{
			Tool: mcp.NewTool("hg_pages_tag",
				mcp.WithDescription("Add, remove, or replace tags on a page. Use 'add' to append tags, 'remove' to delete specific tags, or 'set' to replace all tags."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID"),
				),
				mcp.WithString("add",
					mcp.Description("Comma-separated tags to add"),
				),
				mcp.WithString("remove",
					mcp.Description("Comma-separated tags to remove"),
				),
				mcp.WithString("set",
					mcp.Description("Comma-separated tags to set (replaces all existing tags)"),
				),
			),
			Handler:             handleTag,
			Category:            "pages",
			Subcategory:         "organize",
			Tags:                []string{"pages", "tag", "label", "organize", "notion"},
			UseCases:            []string{"Tag a note", "Organize notes by topic"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("hg_pages_move",
				mcp.WithDescription("Change the category of a page."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID"),
				),
				mcp.WithString("category",
					mcp.Required(),
					mcp.Description("New category (e.g., Notes, Documentation, Journal)"),
				),
			),
			Handler:             handleMove,
			Category:            "pages",
			Subcategory:         "organize",
			Tags:                []string{"pages", "move", "category", "organize", "notion"},
			UseCases:            []string{"Change note category", "Reorganize pages"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("hg_pages_set_status",
				mcp.WithDescription("Change a page's status (Draft, Active, or Archived)."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID"),
				),
				mcp.WithString("status",
					mcp.Required(),
					mcp.Description("New status: Draft, Active, or Archived"),
				),
			),
			Handler:             handleSetStatus,
			Category:            "pages",
			Subcategory:         "organize",
			Tags:                []string{"pages", "status", "workflow", "organize", "notion"},
			UseCases:            []string{"Publish a draft", "Archive a page", "Change page status"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("hg_pages_rename",
				mcp.WithDescription("Rename a page (change its title)."),
				mcp.WithString("page_id",
					mcp.Required(),
					mcp.Description("Notion page ID"),
				),
				mcp.WithString("title",
					mcp.Required(),
					mcp.Description("New page title"),
				),
			),
			Handler:             handleRename,
			Category:            "pages",
			Subcategory:         "organize",
			Tags:                []string{"pages", "rename", "title", "notion"},
			UseCases:            []string{"Rename a note", "Update page title"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},

		// --- Templates ---
		{
			Tool: mcp.NewTool("hg_pages_templates",
				mcp.WithDescription("List pages marked as templates, optionally filtered by category."),
				mcp.WithString("category",
					mcp.Description("Filter templates by category"),
				),
			),
			Handler:             handleTemplates,
			Category:            "pages",
			Subcategory:         "templates",
			Tags:                []string{"pages", "templates", "list", "notion"},
			UseCases:            []string{"Browse note templates", "Find template for new page"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
		},
		{
			Tool: mcp.NewTool("hg_pages_from_template",
				mcp.WithDescription("Create a new page by copying a template's content blocks and properties."),
				mcp.WithString("template_id",
					mcp.Required(),
					mcp.Description("Notion page ID of the template"),
				),
				mcp.WithString("title",
					mcp.Required(),
					mcp.Description("Title for the new page"),
				),
				mcp.WithString("tags",
					mcp.Description("Comma-separated tags for the new page"),
				),
				mcp.WithString("category",
					mcp.Description("Category for the new page (defaults to template's category)"),
				),
			),
			Handler:             handleFromTemplate,
			Category:            "pages",
			Subcategory:         "templates",
			Tags:                []string{"pages", "template", "create", "copy", "notion"},
			UseCases:            []string{"Create note from template", "Stamp out structured pages"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "pages",
			IsWrite:             true,
		},
		// --- Health ---
		{
			Tool: mcp.NewTool("hg_pages_health",
				mcp.WithDescription("Check pages module health: configuration, API connectivity, and page statistics."),
			),
			Handler:             handlePagesHealth,
			Category:            "pages",
			Subcategory:         "status",
			Tags:                []string{"pages", "health", "diagnostics", "status", "notion"},
			UseCases:            []string{"Check pages module health", "Diagnose configuration issues", "View page statistics"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "pages",
		},
	}
}

func init() {
	tools.GetRegistry().RegisterModule(&Module{})
}
