package cr8

import (
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/hairglasses-studio/hg-mcp/internal/mcp/tools"
)

// Module implements the ToolModule interface for CR8 music library tools
type Module struct{}

func (m *Module) Name() string {
	return "cr8"
}

func (m *Module) Description() string {
	return "CR8 music library management tools for DynamoDB/S3 sync, analysis, and maintenance"
}

func (m *Module) Tools() []tools.ToolDefinition {
	return []tools.ToolDefinition{
		// Status & Monitoring
		{
			Tool: mcp.NewTool("cr8_migration_status",
				mcp.WithDescription("Get comprehensive migration status including DynamoDB tables, S3 bucket structure, and rclone jobs"),
			),
			Handler:             handleMigrationStatus,
			Category:            "cr8",
			Subcategory:         "status",
			Tags:                []string{"cr8", "migration", "status", "dynamodb", "s3"},
			UseCases:            []string{"Check migration progress", "Monitor DynamoDB tables", "View S3 bucket structure"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},
		{
			Tool: mcp.NewTool("cr8_verify_sync",
				mcp.WithDescription("Verify S3 and DynamoDB are in sync. Returns matched files, orphaned S3 files, and missing files."),
				mcp.WithNumber("sample_size",
					mcp.Description("Number of orphaned/missing files to sample (default: 20)"),
				),
			),
			Handler:             handleVerifySync,
			Category:            "cr8",
			Subcategory:         "sync",
			Tags:                []string{"cr8", "sync", "verify", "s3", "dynamodb", "consistency"},
			UseCases:            []string{"Verify data consistency", "Find orphaned S3 files", "Identify missing files"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "cr8",
		},

		// Analysis
		{
			Tool: mcp.NewTool("cr8_analysis_stats",
				mcp.WithDescription("Get audio analysis coverage statistics (BPM, key detection rates)"),
			),
			Handler:             handleAnalysisStats,
			Category:            "cr8",
			Subcategory:         "analysis",
			Tags:                []string{"cr8", "analysis", "bpm", "key", "coverage"},
			UseCases:            []string{"Check analysis coverage", "Find unanalyzed tracks", "Monitor BPM/key detection"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},
		{
			Tool: mcp.NewTool("cr8_queue_analysis",
				mcp.WithDescription("Queue unanalyzed tracks for BPM/key analysis"),
				mcp.WithNumber("limit",
					mcp.Description("Maximum tracks to queue (default: all)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview without queuing (default: false)"),
				),
			),
			Handler:             handleQueueAnalysis,
			Category:            "cr8",
			Subcategory:         "analysis",
			Tags:                []string{"cr8", "analysis", "queue", "bpm", "key"},
			UseCases:            []string{"Queue tracks for analysis", "Trigger BPM detection", "Process unanalyzed music"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},
		{
			Tool: mcp.NewTool("cr8_run_analysis",
				mcp.WithDescription("Run analysis worker to process queued tracks. Downloads from S3, analyzes with librosa, updates DynamoDB with BPM/key."),
				mcp.WithNumber("batch",
					mcp.Description("Number of tracks to process (default: 10)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview without updating database (default: false)"),
				),
			),
			Handler:             handleRunAnalysis,
			Category:            "cr8",
			Subcategory:         "analysis",
			Tags:                []string{"cr8", "analysis", "worker", "bpm", "key", "librosa"},
			UseCases:            []string{"Process analysis queue", "Analyze tracks for BPM/key", "Run batch analysis"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Path Management
		{
			Tool: mcp.NewTool("cr8_update_paths",
				mcp.WithDescription("Update DynamoDB track paths from old structure to new unified structure"),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview changes without applying (default: true)"),
				),
				mcp.WithBoolean("verbose",
					mcp.Description("Show each update (default: false)"),
				),
			),
			Handler:             handleUpdatePaths,
			Category:            "cr8",
			Subcategory:         "paths",
			Tags:                []string{"cr8", "paths", "update", "migrate", "structure"},
			UseCases:            []string{"Update track paths", "Migrate to new structure", "Fix path mismatches"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Import
		{
			Tool: mcp.NewTool("cr8_import_s3_tracks",
				mcp.WithDescription("Import orphaned S3 audio files into DynamoDB. Creates track records for files not in database."),
				mcp.WithNumber("limit",
					mcp.Description("Maximum tracks to import (default: all)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview without importing (default: true)"),
				),
			),
			Handler:             handleImportS3Tracks,
			Category:            "cr8",
			Subcategory:         "import",
			Tags:                []string{"cr8", "import", "s3", "tracks", "orphaned"},
			UseCases:            []string{"Import S3 files to DB", "Create track records", "Sync S3 with DynamoDB"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// S3 Operations
		{
			Tool: mcp.NewTool("cr8_s3_structure",
				mcp.WithDescription("Get S3 bucket structure with file counts and sizes per prefix"),
			),
			Handler:             handleS3Structure,
			Category:            "cr8",
			Subcategory:         "s3",
			Tags:                []string{"cr8", "s3", "structure", "storage", "files"},
			UseCases:            []string{"View S3 organization", "Check storage usage", "Audit bucket structure"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},
		{
			Tool: mcp.NewTool("cr8_sync_music",
				mcp.WithDescription("Sync local music folder to S3 using rclone (filters DJ sets >25MB)"),
				mcp.WithString("source",
					mcp.Required(),
					mcp.Description("Source path: 'music' (~/Music) or 'gdrive' (Google Drive) or custom path"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview sync without copying (default: true)"),
				),
			),
			Handler:             handleSyncMusic,
			Category:            "cr8",
			Subcategory:         "sync",
			Tags:                []string{"cr8", "sync", "rclone", "music", "s3"},
			UseCases:            []string{"Sync music to S3", "Backup music library", "Upload new tracks"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// S3 Reorganization
		{
			Tool: mcp.NewTool("cr8_s3_reorganize",
				mcp.WithDescription("Reorganize S3 bucket structure - move files to new path hierarchy"),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview moves without executing (default: true)"),
				),
			),
			Handler:             handleS3Reorganize,
			Category:            "cr8",
			Subcategory:         "s3",
			Tags:                []string{"cr8", "s3", "reorganize", "structure", "migrate"},
			UseCases:            []string{"Reorganize S3 paths", "Migrate to new structure", "Clean up bucket"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Full Migration Verification
		{
			Tool: mcp.NewTool("cr8_verify_migration",
				mcp.WithDescription("Comprehensive migration verification - checks Supabase vs DynamoDB data integrity"),
			),
			Handler:             handleVerifyMigration,
			Category:            "cr8",
			Subcategory:         "migration",
			Tags:                []string{"cr8", "migration", "verify", "supabase", "dynamodb"},
			UseCases:            []string{"Verify migration completeness", "Check data integrity", "Compare source and target"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
		},

		// DynamoDB Import
		{
			Tool: mcp.NewTool("cr8_dynamodb_import",
				mcp.WithDescription("Import JSON data into DynamoDB tables (tracks, playlists, etc.)"),
				mcp.WithString("table",
					mcp.Required(),
					mcp.Description("Target table: 'tracks', 'playlists', 'playlist_tracks'"),
				),
				mcp.WithString("json_file",
					mcp.Description("Path to JSON file (default: exports/{table}.json)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview import without writing (default: true)"),
				),
			),
			Handler:             handleDynamoDBImport,
			Category:            "cr8",
			Subcategory:         "import",
			Tags:                []string{"cr8", "dynamodb", "import", "json", "migrate"},
			UseCases:            []string{"Import track data", "Restore from backup", "Migrate from JSON"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Supabase Export
		{
			Tool: mcp.NewTool("cr8_supabase_export",
				mcp.WithDescription("Export data from Supabase to JSON files for migration"),
				mcp.WithString("table",
					mcp.Description("Table to export: 'tracks', 'playlists', 'all' (default: all)"),
				),
			),
			Handler:             handleSupabaseExport,
			Category:            "cr8",
			Subcategory:         "export",
			Tags:                []string{"cr8", "supabase", "export", "json", "backup"},
			UseCases:            []string{"Export from Supabase", "Create migration data", "Backup database"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "cr8",
		},

		// Consolidated Status
		{
			Tool: mcp.NewTool("cr8_status",
				mcp.WithDescription("Get complete CR8 system status: tracks, analysis coverage, queue depth, S3 storage, and ETA for analysis completion"),
			),
			Handler:             handleCR8Status,
			Category:            "cr8",
			Subcategory:         "status",
			Tags:                []string{"cr8", "status", "consolidated", "overview", "dashboard"},
			UseCases:            []string{"Get system overview", "Check analysis progress", "Monitor queue status"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "cr8",
		},

		// Queue Status
		{
			Tool: mcp.NewTool("cr8_queue_status",
				mcp.WithDescription("Get detailed analysis queue status: pending/processing/completed counts, recent failures, and ETA"),
				mcp.WithBoolean("failures",
					mcp.Description("Show recent failure details (default: false)"),
				),
			),
			Handler:             handleQueueStatus,
			Category:            "cr8",
			Subcategory:         "status",
			Tags:                []string{"cr8", "queue", "status", "analysis", "progress"},
			UseCases:            []string{"Check queue progress", "View processing rate", "Debug failures"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},

		// Playlist Sync
		{
			Tool: mcp.NewTool("cr8_sync_likes",
				mcp.WithDescription("Sync new tracks from all playlists (SoundCloud likes, YouTube, etc.) to S3. Fetches new tracks, downloads them, and queues for analysis."),
				mcp.WithNumber("playlist_id",
					mcp.Description("Sync specific playlist by ID (optional)"),
				),
				mcp.WithString("username",
					mcp.Description("Sync playlists for specific username (optional)"),
				),
				mcp.WithString("service",
					mcp.Description("Filter by service: soundcloud, youtube (optional)"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Max new tracks to process per playlist (default: all)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview without downloading (default: false)"),
				),
			),
			Handler:             handleSyncLikes,
			Category:            "cr8",
			Subcategory:         "sync",
			Tags:                []string{"cr8", "sync", "likes", "playlist", "soundcloud", "youtube", "s3"},
			UseCases:            []string{"Sync new playlist likes", "Download new tracks to S3", "Keep playlists updated"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Rekordbox Sync
		{
			Tool: mcp.NewTool("cr8_sync_rekordbox",
				mcp.WithDescription("Sync CR8 playlists to Rekordbox. Maps S3 paths to local files and creates/updates Rekordbox playlists."),
				mcp.WithNumber("playlist_id",
					mcp.Description("Sync specific playlist by ID (optional)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview sync without making changes (default: true)"),
				),
				mcp.WithBoolean("download",
					mcp.Description("Download missing files from S3 (default: false)"),
				),
				mcp.WithBoolean("sync_local",
					mcp.Description("Sync S3 to local folder first using rclone (default: false)"),
				),
			),
			Handler:             handleSyncRekordbox,
			Category:            "cr8",
			Subcategory:         "sync",
			Tags:                []string{"cr8", "rekordbox", "sync", "playlist", "dj"},
			UseCases:            []string{"Sync playlists to Rekordbox", "Update DJ library", "Auto-sync new tracks"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Path Migration
		{
			Tool: mcp.NewTool("cr8_migrate_paths",
				mcp.WithDescription("Migrate tracks from flat S3 paths (downloads/user/file.m4a) to full DJ Crates structure (downloads/dj_crates/user/playlist/file.m4a). Moves S3 objects and updates DynamoDB records."),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview moves without executing (default: true)"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum tracks to migrate (default: all)"),
				),
				mcp.WithBoolean("verbose",
					mcp.Description("Show detailed output (default: false)"),
				),
			),
			Handler:             handleMigratePaths,
			Category:            "cr8",
			Subcategory:         "migration",
			Tags:                []string{"cr8", "migrate", "paths", "s3", "reorganize"},
			UseCases:            []string{"Fix track paths", "Migrate to new structure", "Reorganize S3 files"},
			Complexity:          tools.ComplexityComplex,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Rekordbox Status
		{
			Tool: mcp.NewTool("cr8_rekordbox_status",
				mcp.WithDescription("Get Rekordbox library status, local file counts, and sync progress between CR8 playlists and Rekordbox"),
			),
			Handler:             handleRekordboxStatus,
			Category:            "cr8",
			Subcategory:         "rekordbox",
			Tags:                []string{"cr8", "rekordbox", "status", "sync", "dj"},
			UseCases:            []string{"Check Rekordbox sync status", "View library stats", "See which playlists need syncing"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},

		// S3 to Local Sync
		{
			Tool: mcp.NewTool("cr8_s3_to_local",
				mcp.WithDescription("Sync audio files from S3 to local ~/Music/CR8 folder using rclone. Downloads new and updated tracks."),
				mcp.WithString("prefix",
					mcp.Description("S3 prefix to sync: 'downloads', 'users', or specific path (default: downloads)"),
				),
				mcp.WithBoolean("dry_run",
					mcp.Description("Preview sync without downloading (default: true)"),
				),
			),
			Handler:             handleS3ToLocal,
			Category:            "cr8",
			Subcategory:         "sync",
			Tags:                []string{"cr8", "s3", "local", "sync", "rclone", "download"},
			UseCases:            []string{"Download music from S3", "Sync cloud to local", "Update local library"},
			Complexity:          tools.ComplexityModerate,
			CircuitBreakerGroup: "cr8",
			IsWrite:             true,
		},

		// Sync Status
		{
			Tool: mcp.NewTool("cr8_sync_status",
				mcp.WithDescription("Get sync state and history for playlists. Shows progress, resume state, and recent sync logs."),
				mcp.WithNumber("playlist_id",
					mcp.Description("Filter by playlist ID (optional)"),
				),
				mcp.WithBoolean("logs",
					mcp.Description("Include recent sync logs (default: false)"),
				),
				mcp.WithBoolean("json",
					mcp.Description("Output as JSON (default: false)"),
				),
				mcp.WithNumber("reset",
					mcp.Description("Reset sync state for playlist ID (allows re-sync from start)"),
				),
			),
			Handler:             handleSyncStatus,
			Category:            "cr8",
			Subcategory:         "sync",
			Tags:                []string{"cr8", "sync", "status", "resume", "logs"},
			UseCases:            []string{"Check sync progress", "View sync history", "Debug failed syncs", "Reset sync state"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},

		// Playlist List (lightweight)
		{
			Tool: mcp.NewTool("cr8_playlist_list",
				mcp.WithDescription("List CR8 playlists with minimal output. Returns ID, service, track count, and name."),
				mcp.WithString("service",
					mcp.Description("Filter by service: soundcloud, youtube (optional)"),
				),
				mcp.WithBoolean("all",
					mcp.Description("Include disabled playlists (default: false)"),
				),
				mcp.WithBoolean("json",
					mcp.Description("Output as compact JSON (default: false)"),
				),
			),
			Handler:             handlePlaylistList,
			Category:            "cr8",
			Subcategory:         "playlist",
			Tags:                []string{"cr8", "playlist", "list", "lightweight"},
			UseCases:            []string{"List playlists quickly", "Get playlist IDs", "Low-token playlist lookup"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},

		// Track Search
		{
			Tool: mcp.NewTool("cr8_track_search",
				mcp.WithDescription("Search tracks by text, BPM range, key, or analysis status"),
				mcp.WithString("query",
					mcp.Description("Search text (matches artist or title)"),
				),
				mcp.WithString("bpm",
					mcp.Description("BPM filter: single value (e.g., '128') or range (e.g., '120-130')"),
				),
				mcp.WithString("key",
					mcp.Description("Musical key filter (e.g., 'Am', 'C')"),
				),
				mcp.WithString("camelot",
					mcp.Description("Camelot key filter (e.g., '8A', '5B')"),
				),
				mcp.WithBoolean("unanalyzed",
					mcp.Description("Only show unanalyzed tracks (default: false)"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum results (default: 50)"),
				),
			),
			Handler:             handleTrackSearch,
			Category:            "cr8",
			Subcategory:         "search",
			Tags:                []string{"cr8", "search", "tracks", "bpm", "key", "query"},
			UseCases:            []string{"Find tracks by artist", "Search by BPM range", "Find tracks in key"},
			Complexity:          tools.ComplexitySimple,
			CircuitBreakerGroup: "cr8",
		},
	}
}

// init registers this module with the global registry
func init() {
	tools.GetRegistry().RegisterModule(&Module{})
}
