# Per-machine monitor config
# XEC ES-G32C1Q (left)
monitor = DP-1, 2560x1440@60, 0x0, 2

# Samsung LC49G95T ultrawide (right)
monitor = DP-2, 5120x1440@120, 1280x0, 2

# Fallback for hotplug
monitor = , preferred, auto, 2
