[scratchpads.term]
command = "ghostty --class=scratchpad"
class = "scratchpad"
size = [80, 70]
animation = "fromTop"

[scratchpads.volume]
command = "pavucontrol"
class = "pavucontrol"
size = [40, 60]
animation = "fromRight"

[scratchpads.files]
command = "thunar"
class = "thunar"
size = [60, 60]
animation = "fromLeft"
