#!/usr/bin/env bash
# eww-theme-gen.sh — Generate eww color overrides from wallpaper using matugen.
# Called by wallpaper-cycle.sh after setting a new wallpaper.
# Writes ~/.config/eww/theme-colors.scss with accent color variables.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EWW_DIR="$HOME/.config/eww"
THEME_FILE="$EWW_DIR/theme-colors.scss"

# Find current wallpaper
WALLPAPER=""
STATE_FILE="$HOME/.local/state/swww/current"
if [[ -f "$STATE_FILE" ]]; then
  WALLPAPER=$(cat "$STATE_FILE" | head -1)
fi

# If no wallpaper or it's a shader, keep Snazzy palette
if [[ -z "$WALLPAPER" ]] || [[ ! -f "$WALLPAPER" ]]; then
  # Write empty overrides (Snazzy defaults apply)
  cat > "$THEME_FILE" << 'EOF'
// Theme: Snazzy (default — no wallpaper detected)
// Generated by eww-theme-gen.sh
EOF
  exit 0
fi

# Check if matugen is installed
if ! command -v matugen &>/dev/null; then
  cat > "$THEME_FILE" << 'EOF'
// Theme: Snazzy (default — matugen not installed)
// Install: sudo pacman -S matugen
EOF
  exit 0
fi

# Generate Material Design 3 palette from wallpaper
PALETTE=$(matugen color -j hex "$WALLPAPER" 2>/dev/null || echo "")
if [[ -z "$PALETTE" ]]; then
  exit 0
fi

# Extract key colors
PRIMARY=$(echo "$PALETTE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('colors',{}).get('dark',{}).get('primary','#57c7ff'))" 2>/dev/null || echo "#57c7ff")
SECONDARY=$(echo "$PALETTE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('colors',{}).get('dark',{}).get('secondary','#ff6ac1'))" 2>/dev/null || echo "#ff6ac1")
TERTIARY=$(echo "$PALETTE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('colors',{}).get('dark',{}).get('tertiary','#5af78e'))" 2>/dev/null || echo "#5af78e")

cat > "$THEME_FILE" << EOF
// Theme: Generated from $(basename "$WALLPAPER")
// Generated by eww-theme-gen.sh at $(date '+%Y-%m-%d %H:%M')
\$theme-primary: ${PRIMARY};
\$theme-secondary: ${SECONDARY};
\$theme-tertiary: ${TERTIARY};
EOF
