#!/usr/bin/env bash
set -euo pipefail

# gen-kitty-theme-playlist.sh
#
# Generate a kitty theme playlist file from the vendored kitty-themes
# metadata. Defaults produce a massive dark-only community playlist at
# kitty/themes/playlists/ambient.txt, sourced from kitty/themes/themes.json
# (copied from kovidgoyal/kitty-themes). Idempotent — re-running on an
# unchanged input is byte-stable.

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]:-$0}")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
source "$SCRIPT_DIR/lib/hg-core.sh"

INPUT="$HG_DOTFILES/kitty/themes/themes.json"
OUTPUT="$HG_DOTFILES/kitty/themes/playlists/ambient.txt"
MODE="dark"

usage() {
  cat <<EOF
Usage: gen-kitty-theme-playlist.sh [options]

Options:
  --input <path>   Source themes.json (default: $INPUT)
  --output <path>  Target playlist file (default: $OUTPUT)
  --mode <dark|light|all>
                   Filter mode (default: dark)
  -h, --help       Show this message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input) INPUT="${2:?missing --input value}"; shift 2 ;;
    --output) OUTPUT="${2:?missing --output value}"; shift 2 ;;
    --mode) MODE="${2:?missing --mode value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) hg_die "Unknown option: $1" ;;
  esac
done

hg_require jq
[[ -f "$INPUT" ]] || hg_die "Missing input: $INPUT"

case "$MODE" in
  dark)  filter='.[] | select(.is_dark == true) | .name' ;;
  light) filter='.[] | select(.is_dark != true) | .name' ;;
  all)   filter='.[] | .name' ;;
  *) hg_die "Unknown mode: $MODE (expected dark|light|all)" ;;
esac

mkdir -p "$(dirname "$OUTPUT")"

rel_input="${INPUT#"$HG_DOTFILES"/}"
tmp="${OUTPUT}.tmp"
{
  printf '# kitty theme playlist — generated by scripts/gen-kitty-theme-playlist.sh\n'
  printf '# source: %s (mode=%s)\n' "$rel_input" "$MODE"
  printf '# do not edit by hand; re-run the generator to refresh\n'
  jq -r "$filter" "$INPUT" | LC_ALL=C sort -u
} > "$tmp"

if [[ -f "$OUTPUT" ]] && cmp -s "$tmp" "$OUTPUT"; then
  rm -f "$tmp"
  hg_ok "$OUTPUT unchanged ($(grep -cv '^#' "$OUTPUT") themes)"
  exit 0
fi

mv "$tmp" "$OUTPUT"
hg_ok "$OUTPUT written ($(grep -cv '^#' "$OUTPUT") themes, mode=$MODE)"
