#!/usr/bin/env bash
# hg-gitignore.sh — Assemble a .gitignore from shared templates.
# Usage: hg-gitignore.sh [go|node|python|hybrid]
# Outputs to stdout. Pipe to .gitignore:
#   hg-gitignore.sh go > .gitignore
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GIT_DIR="$SCRIPT_DIR/../git"

LANG="${1:-}"

if [[ -z "$LANG" ]]; then
  # Auto-detect from current directory
  if [[ -f go.mod ]] && [[ -f package.json ]]; then
    LANG="hybrid"
  elif [[ -f go.mod ]]; then
    LANG="go"
  elif [[ -f package.json ]]; then
    LANG="node"
  elif [[ -f pyproject.toml ]] || [[ -f requirements.txt ]]; then
    LANG="python"
  else
    echo "Usage: hg-gitignore.sh [go|node|python|hybrid]" >&2
    exit 1
  fi
fi

echo "# Generated by hg-gitignore.sh ($LANG)"
echo "# Edit the project-specific section at the bottom."
echo ""
cat "$GIT_DIR/gitignore-base"

case "$LANG" in
  go)
    echo ""
    cat "$GIT_DIR/gitignore-go"
    ;;
  node)
    echo ""
    cat "$GIT_DIR/gitignore-node"
    ;;
  python)
    echo ""
    cat "$GIT_DIR/gitignore-python"
    ;;
  hybrid)
    echo ""
    cat "$GIT_DIR/gitignore-go"
    echo ""
    cat "$GIT_DIR/gitignore-node"
    ;;
  *)
    echo "Unknown language: $LANG (use go|node|python|hybrid)" >&2
    exit 1
    ;;
esac

echo ""
echo "# ── Project-specific ─────────────────────────"
echo "# Add repo-specific patterns below this line."
