#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/hg-core.sh"

MODE="write"

for arg in "$@"; do
  case "$arg" in
    --dry-run) MODE="dry-run" ;;
    --check)   MODE="check" ;;
    *)
      hg_die "Unknown argument: $arg"
      ;;
  esac
done

CLAUDE_COMMANDS="$HOME/.claude/commands"
AGENTS_SKILLS="$HOME/.agents/skills"

[[ -d "$CLAUDE_COMMANDS" ]] || hg_die "Claude commands directory not found: $CLAUDE_COMMANDS"

# Skills that are Claude Code-specific (use claude_* MCP tools, session recovery, etc.)
# These have no Codex equivalent and should not be synced.
CLAUDE_ONLY_SKILLS=(
  session-status
  recover
  recover-session
  recovery-dashboard
  workspace-snapshot
  session-diff
  session-autopsy
  recovery-verify
  crash-report
)

is_claude_only() {
  local name="$1"
  for skip in "${CLAUDE_ONLY_SKILLS[@]}"; do
    [[ "$name" == "$skip" ]] && return 0
  done
  return 1
}

# Convert kebab-case filename to snake_case skill name (Codex convention)
to_skill_name() {
  local name="$1"
  printf '%s' "$name" | tr '-' '_'
}

# Extract the first non-empty line as the description, trimmed cleanly
extract_description() {
  local file="$1"
  head -1 "$file" | sed 's/\. *$//; s/:$//; s/^ *//'
}

# Transform $ARGUMENTS references in the body for Codex compatibility.
# Codex receives arguments from conversation context, so we replace the
# placeholder with a note. The natural language instructions remain identical.
transform_body() {
  local file="$1"
  sed \
    -e 's/\$ARGUMENTS/[user-provided arguments]/g' \
    -e 's|`/reconnect`|reconnect all MCP servers|g' \
    -e 's|`/commit`|`git commit`|g' \
    -e 's|`/loop \([^`]*\)`|set up a recurring loop (\1)|g' \
    -e 's|`/pipeline \([^`]*\)`|re-run the pipeline (\1)|g' \
    -e 's| /commit| git commit|g' \
    -e 's| /pipeline | the pipeline |g' \
    -e 's|inside `/loop`|in recurring mode|g' \
    -e 's|`/loop`|a recurring loop|g' \
    -e 's| /loop | a recurring loop |g' \
    -e 's|Run `/reconnect`|Reconnect all MCP servers|g' \
    "$file"
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

pending_changes=0
declare -A desired_dirs=()

sync_file() {
  local staged="$1"
  local target="$2"
  local label="$3"

  if [[ -f "$target" ]] && cmp -s "$staged" "$target"; then
    return
  fi

  pending_changes=1
  case "$MODE" in
    write)
      mkdir -p "$(dirname "$target")"
      cp "$staged" "$target"
      hg_ok "$label: $target"
      ;;
    dry-run)
      hg_warn "Would update $label: $target"
      ;;
    check)
      hg_warn "Out of date $label: $target"
      ;;
  esac
}

portable_count=0
skipped_count=0

for source_file in "$CLAUDE_COMMANDS"/*.md; do
  [[ -f "$source_file" ]] || continue

  basename_md="$(basename "$source_file")"
  raw_name="${basename_md%.md}"

  if is_claude_only "$raw_name"; then
    skipped_count=$((skipped_count + 1))
    continue
  fi

  portable_count=$((portable_count + 1))
  skill_name="$(to_skill_name "$raw_name")"
  desired_dirs["$skill_name"]=1
  description="$(extract_description "$source_file")"

  staged="$tmpdir/${skill_name}.md"
  {
    printf '%s\n' '---'
    printf 'name: %s\n' "$skill_name"
    printf 'description: >-\n'
    printf '  %s\n' "$description"
    printf '%s\n\n' '---'
    printf '<!-- GENERATED BY hg-global-skill-sync.sh FROM ~/.claude/commands/%s; DO NOT EDIT -->\n\n' "$basename_md"
    transform_body "$source_file"
  } >"$staged"

  sync_file "$staged" "$AGENTS_SKILLS/$skill_name/SKILL.md" "Synced global skill"
done

# Purge stale skill directories that are no longer generated
if [[ -d "$AGENTS_SKILLS" ]]; then
  while IFS= read -r dir; do
    skill_name="$(basename "$dir")"
    # Only purge directories that have our generation marker
    if [[ -f "$dir/SKILL.md" ]] && grep -q 'GENERATED BY hg-global-skill-sync.sh' "$dir/SKILL.md" 2>/dev/null; then
      if [[ -z "${desired_dirs[$skill_name]:-}" ]]; then
        pending_changes=1
        case "$MODE" in
          write)
            rm -rf "$dir"
            hg_ok "Removed stale global skill: $dir"
            ;;
          dry-run)
            hg_warn "Would remove stale global skill: $dir"
            ;;
          check)
            hg_warn "Unexpected global skill: $dir"
            ;;
        esac
      fi
    fi
  done < <(find "$AGENTS_SKILLS" -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | sort)
fi

case "$MODE" in
  write)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "Global skills already synchronized ($portable_count portable, $skipped_count Claude-only skipped)"
    else
      hg_info "Synchronized $portable_count portable skills ($skipped_count Claude-only skipped)"
    fi
    ;;
  dry-run)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "No global skill changes needed ($portable_count portable, $skipped_count Claude-only)"
    fi
    ;;
  check)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "Global skills are up to date ($portable_count portable, $skipped_count Claude-only)"
    else
      exit 1
    fi
    ;;
esac
