#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/hg-core.sh"

REPO_PATH="${1:-$PWD}"
MODE="write"

if [[ $# -gt 0 ]]; then
  shift
fi

for arg in "$@"; do
  case "$arg" in
    --dry-run) MODE="dry-run" ;;
    --check)   MODE="check" ;;
    *)
      hg_die "Unknown argument: $arg"
      ;;
  esac
done

REPO_PATH="$(cd "$REPO_PATH" && pwd)"
REPO_NAME="$(basename "$REPO_PATH")"
CODEX_DIR="$REPO_PATH/.codex/agents"

if [[ ! -d "$CODEX_DIR" ]] || ! find "$CODEX_DIR" -maxdepth 1 -type f -name '*.toml' | grep -q .; then
  hg_info "$REPO_NAME: no canonical Codex role pack found"
  exit 0
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

pending_changes=0
declare -A expected_claude=()
declare -A expected_gemini=()

extract_quoted_value() {
  local file="$1"
  local key="$2"
  awk -v key="$key" '
    $0 ~ ("^" key "[[:space:]]*=") {
      sub("^[^=]*=[[:space:]]*", "", $0)
      gsub(/^"/, "", $0)
      gsub(/"$/, "", $0)
      print
      exit
    }
  ' "$file"
}

extract_multiline_value() {
  local file="$1"
  local key="$2"
  awk -v key="$key" '
    $0 ~ ("^" key "[[:space:]]*=[[:space:]]*\"\"\"") {
      sub("^[^\"]*\"\"\"", "", $0)
      in_block = 1
      if (length($0) > 0) {
        print
      }
      next
    }
    in_block {
      if (index($0, "\"\"\"") > 0) {
        sub(/""".*/, "", $0)
        if (length($0) > 0) {
          print
        }
        exit
      }
      print
    }
  ' "$file"
}

toml_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

sync_file() {
  local staged="$1"
  local target="$2"
  local label="$3"

  if [[ -f "$target" ]] && cmp -s "$staged" "$target"; then
    return
  fi

  pending_changes=1
  case "$MODE" in
    write)
      mkdir -p "$(dirname "$target")"
      cp "$staged" "$target"
      hg_ok "$label: ${target#$REPO_PATH/}"
      ;;
    dry-run)
      hg_warn "Would update $label: ${target#$REPO_PATH/}"
      ;;
    check)
      hg_warn "Out of date $label: ${target#$REPO_PATH/}"
      ;;
  esac
}

purge_generated_files() {
  local base_dir="$1"
  local ext="$2"
  local expected_name="$3"
  local label="$4"
  local -n expected="$expected_name"

  [[ -d "$base_dir" ]] || return 0

  while IFS= read -r path; do
    local rel="${path#$base_dir/}"
    if [[ -n "${expected[$rel]:-}" ]]; then
      continue
    fi
    if ! grep -q 'GENERATED BY hg-provider-role-sync.sh' "$path"; then
      continue
    fi

    pending_changes=1
    case "$MODE" in
      write)
        rm -f "$path"
        hg_ok "Removed stale $label: ${path#$REPO_PATH/}"
        ;;
      dry-run)
        hg_warn "Would remove stale $label: ${path#$REPO_PATH/}"
        ;;
      check)
        hg_warn "Unexpected generated $label: ${path#$REPO_PATH/}"
        ;;
    esac
  done < <(find "$base_dir" -type f -name "*.${ext}" | sort)
}

while IFS= read -r codex_file; do
  base="$(basename "$codex_file" .toml)"
  description="$(extract_quoted_value "$codex_file" "description")"
  prompt="$(extract_multiline_value "$codex_file" "developer_instructions")"

  [[ -n "$base" ]] || hg_die "Invalid Codex role filename: $codex_file"
  [[ -n "$description" ]] || hg_die "Missing description in $codex_file"
  [[ -n "$prompt" ]] || hg_die "Missing developer_instructions in $codex_file"

  if grep -q '"""' <<<"$prompt"; then
    hg_die "Unsupported triple quote sequence in $codex_file developer_instructions"
  fi

  expected_claude["$base.md"]=1
  expected_gemini["$base.toml"]=1

  claude_file="$tmpdir/$base.claude.md"
  {
    printf '%s\n' '---'
    printf 'description: %s\n' "$description"
    printf '%s\n\n' '---'
    printf '<!-- GENERATED BY hg-provider-role-sync.sh FROM .codex/agents/%s.toml; DO NOT EDIT -->\n\n' "$base"
    printf '%s\n' "$prompt"
  } >"$claude_file"
  sync_file "$claude_file" "$REPO_PATH/.claude/agents/$base.md" "Synced Claude role"

  gemini_file="$tmpdir/$base.gemini.toml"
  {
    printf '# GENERATED BY hg-provider-role-sync.sh FROM .codex/agents/%s.toml; DO NOT EDIT\n' "$base"
    printf 'description = "%s"\n' "$(toml_escape "$description")"
    printf 'prompt = """\n%s\n"""\n' "$prompt"
  } >"$gemini_file"
  sync_file "$gemini_file" "$REPO_PATH/.gemini/commands/$base.toml" "Synced Gemini command"
done < <(find "$CODEX_DIR" -maxdepth 1 -type f -name '*.toml' | sort)

purge_generated_files "$REPO_PATH/.claude/agents" "md" expected_claude "Claude role"
purge_generated_files "$REPO_PATH/.gemini/commands" "toml" expected_gemini "Gemini command"

case "$MODE" in
  write)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "$REPO_NAME: provider role surfaces already synchronized"
    fi
    ;;
  dry-run)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "$REPO_NAME: no provider role changes needed"
    fi
    ;;
  check)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "$REPO_NAME: provider role surfaces are up to date"
    else
      exit 1
    fi
    ;;
esac
