#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/hg-core.sh"

REPO_PATH="${1:-$PWD}"
MODE="write"

if [[ $# -gt 0 ]]; then
  shift
fi

for arg in "$@"; do
  case "$arg" in
    --dry-run) MODE="dry-run" ;;
    --check)   MODE="check" ;;
    *)
      hg_die "Unknown argument: $arg"
      ;;
  esac
done

hg_require jq

REPO_PATH="$(cd "$REPO_PATH" && pwd)"
REPO_NAME="$(basename "$REPO_PATH")"
MANIFEST="$REPO_PATH/.agents/skills/surface.yaml"

[[ -f "$MANIFEST" ]] || hg_die "Missing canonical skill manifest: $MANIFEST"

if ! jq -e '.version == 1 and (.skills | type == "array")' "$MANIFEST" >/dev/null 2>&1; then
  hg_die "Invalid skill manifest (expected JSON/YAML 1.2 with version=1 and skills[]): $MANIFEST"
fi

PLUGIN_ROOT="$(jq -r --arg repo "$REPO_NAME" '.plugin_root // $repo' "$MANIFEST")"
CLAUDE_MANAGED="$(jq -r 'if has("claude_managed") then .claude_managed else true end' "$MANIFEST")"
PLUGIN_MANAGED="$(jq -r 'if has("plugin_managed") then .plugin_managed else true end' "$MANIFEST")"

if [[ "$CLAUDE_MANAGED" != "true" && "$CLAUDE_MANAGED" != "false" ]]; then
  hg_die "claude_managed must be true or false in $MANIFEST"
fi
if [[ "$PLUGIN_MANAGED" != "true" && "$PLUGIN_MANAGED" != "false" ]]; then
  hg_die "plugin_managed must be true or false in $MANIFEST"
fi

SKILLS_REF_AVAILABLE=0
if command -v skills-ref >/dev/null 2>&1; then
  SKILLS_REF_AVAILABLE=1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

pending_changes=0
declare -A desired_claude_dirs=()
declare -A desired_plugin_dirs=()

yaml_quote() {
  local value="$1"
  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

extract_frontmatter_value() {
  local file="$1"
  local key="$2"
  local value
  value=$(
    awk -v key="$key" '
      BEGIN { in_frontmatter = 0 }
      NR == 1 && $0 == "---" { in_frontmatter = 1; next }
      in_frontmatter && $0 == "---" { exit }
      in_frontmatter && $0 ~ ("^" key ":[[:space:]]*") {
        sub("^" key ":[[:space:]]*", "", $0)
        print
        exit
      }
    ' "$file"
  )

  value="${value#\"}"
  value="${value%\"}"
  value="${value#\'}"
  value="${value%\'}"
  printf '%s' "$value"
}

extract_allowed_tools() {
  local file="$1"
  awk '
    BEGIN { in_frontmatter = 0; in_tools = 0 }
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { exit }
    in_frontmatter && /^allowed-tools:[[:space:]]*$/ { in_tools = 1; next }
    in_tools && /^[[:space:]]*-[[:space:]]+/ {
      sub(/^[[:space:]]*-[[:space:]]+/, "", $0)
      print
      next
    }
    in_tools && /^[[:space:]]*$/ { next }
    in_tools { exit }
  ' "$file"
}

extract_body() {
  local file="$1"
  awk '
    BEGIN { in_frontmatter = 0; body = 0 }
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { body = 1; next }
    body { print }
  ' "$file"
}

validate_portable_frontmatter() {
  local file="$1"
  local invalid
  invalid=$(
    awk '
      BEGIN { in_frontmatter = 0 }
      NR == 1 && $0 == "---" { in_frontmatter = 1; next }
      in_frontmatter && $0 == "---" { exit }
      !in_frontmatter { next }
      /^[[:space:]]*$/ { next }
      /^[[:space:]]*-[[:space:]]+/ { next }
      match($0, /^([A-Za-z0-9_-]+):/, parts) {
        key = parts[1]
        if (key != "name" && key != "description" && key != "allowed-tools") {
          print key
        }
        next
      }
      { print "__INVALID__" }
    ' "$file" | sort -u
  )

  if [[ -n "$invalid" ]]; then
    hg_die "Non-portable frontmatter in $file: $invalid"
  fi
}

render_skill() {
  local output="$1"
  local name="$2"
  local description="$3"
  local canonical_name="$4"
  local canonical_path="$5"
  local banner="$6"
  local tools_file="$7"
  local body_file="$8"

  {
    printf '%s\n' '---'
    printf 'name: %s\n' "$name"
    printf 'description: %s\n' "$(yaml_quote "$description")"
    if [[ -s "$tools_file" ]]; then
      printf '%s\n' 'allowed-tools:'
      while IFS= read -r tool; do
        [[ -n "$tool" ]] || continue
        printf '  - %s\n' "$tool"
      done <"$tools_file"
    fi
    printf '%s\n\n' '---'
    printf '<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/%s/SKILL.md; DO NOT EDIT -->\n' "$canonical_name"
    if [[ -n "$banner" ]]; then
      printf '\n%s\n\n' "$banner"
    else
      printf '\n'
    fi
    cat "$body_file"
  } >"$output"

  if grep -q '\.claude/commands/' "$output"; then
    hg_die "Generated skill still references .claude/commands/: $canonical_path"
  fi
}

sync_file() {
  local staged="$1"
  local target="$2"
  local label="$3"

  if [[ -f "$target" ]] && cmp -s "$staged" "$target"; then
    return
  fi

  pending_changes=1
  case "$MODE" in
    write)
      mkdir -p "$(dirname "$target")"
      cp "$staged" "$target"
      hg_ok "$label: ${target#$REPO_PATH/}"
      ;;
    dry-run)
      hg_warn "Would update $label: ${target#$REPO_PATH/}"
      ;;
    check)
      hg_warn "Out of date $label: ${target#$REPO_PATH/}"
      ;;
  esac
}

purge_skill_dirs() {
  local base_dir="$1"
  local label="$2"
  local expected_name="$3"
  local managed="$4"
  local -n expected="$expected_name"

  [[ "$managed" == "true" ]] || return 0
  [[ -d "$base_dir" ]] || return 0

  while IFS= read -r dir; do
    local skill_name
    skill_name="$(basename "$dir")"
    if [[ -n "${expected[$skill_name]:-}" ]]; then
      continue
    fi

    pending_changes=1
    case "$MODE" in
      write)
        rm -rf "$dir"
        hg_ok "Removed stale $label: ${dir#$REPO_PATH/}"
        ;;
      dry-run)
        hg_warn "Would remove stale $label: ${dir#$REPO_PATH/}"
        ;;
      check)
        hg_warn "Unexpected $label: ${dir#$REPO_PATH/}"
        ;;
    esac
  done < <(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | sort)
}

register_claude_dir() {
  local skill_name="$1"
  if [[ -n "${desired_claude_dirs[$skill_name]:-}" ]]; then
    hg_die "Duplicate managed Claude skill name in $MANIFEST: $skill_name"
  fi
  desired_claude_dirs["$skill_name"]=1
}

register_plugin_dir() {
  local skill_name="$1"
  if [[ -n "${desired_plugin_dirs[$skill_name]:-}" ]]; then
    hg_die "Duplicate managed plugin skill name in $MANIFEST: $skill_name"
  fi
  desired_plugin_dirs["$skill_name"]=1
}

while IFS= read -r skill_json; do
  canonical_name="$(jq -r '.name' <<<"$skill_json")"
  export_plugin="$(jq -r 'if has("export_plugin") then .export_plugin else false end' <<<"$skill_json")"
  include_canonical_alias="$(jq -r 'if has("claude_include_canonical") then .claude_include_canonical else true end' <<<"$skill_json")"
  canonical_path="$REPO_PATH/.agents/skills/$canonical_name/SKILL.md"

  [[ -f "$canonical_path" ]] || hg_die "Missing canonical skill: $canonical_path"
  validate_portable_frontmatter "$canonical_path"

  canonical_frontmatter_name="$(extract_frontmatter_value "$canonical_path" 'name')"
  canonical_description="$(extract_frontmatter_value "$canonical_path" 'description')"

  [[ -n "$canonical_frontmatter_name" ]] || hg_die "Missing name frontmatter in $canonical_path"
  [[ -n "$canonical_description" ]] || hg_die "Missing description frontmatter in $canonical_path"
  [[ "$canonical_frontmatter_name" == "$canonical_name" ]] || hg_die "Canonical skill name mismatch in $canonical_path (expected $canonical_name, found $canonical_frontmatter_name)"

  if [[ "$SKILLS_REF_AVAILABLE" -eq 1 ]]; then
    skills-ref validate "$canonical_path" >/dev/null
  fi

  tools_file="$tmpdir/${canonical_name}.tools"
  body_file="$tmpdir/${canonical_name}.body"
  extract_allowed_tools "$canonical_path" >"$tools_file"
  extract_body "$canonical_path" >"$body_file"

  if [[ "$include_canonical_alias" == "true" ]]; then
    register_claude_dir "$canonical_name"
    claude_file="$tmpdir/${canonical_name}.claude"
    render_skill \
      "$claude_file" \
      "$canonical_name" \
      "$canonical_description" \
      "$canonical_name" \
      "$canonical_path" \
      "Compatibility mirror of the canonical \`$canonical_name\` skill." \
      "$tools_file" \
      "$body_file"
    sync_file "$claude_file" "$REPO_PATH/.claude/skills/$canonical_name/SKILL.md" "Synced Claude skill"
  elif [[ "$include_canonical_alias" != "false" ]]; then
    hg_die "claude_include_canonical must be true or false for $canonical_name"
  fi

  while IFS= read -r alias_json; do
    alias_name="$(jq -r 'if type == "object" then .name else . end' <<<"$alias_json")"
    alias_description="$(jq -r 'if type == "object" then (.description // "") else "" end' <<<"$alias_json")"
    [[ -n "$alias_name" && "$alias_name" != "null" ]] || hg_die "Invalid claude_aliases entry for $canonical_name in $MANIFEST"
    [[ "$alias_name" != "$canonical_name" ]] || hg_die "Alias must not duplicate canonical skill name: $canonical_name"
    if [[ -z "$alias_description" || "$alias_description" == "null" ]]; then
      alias_description="Compatibility alias for the $canonical_name workflow."
    fi

    register_claude_dir "$alias_name"
    alias_file="$tmpdir/${canonical_name}.${alias_name}.claude"
    render_skill \
      "$alias_file" \
      "$alias_name" \
      "$alias_description" \
      "$canonical_name" \
      "$canonical_path" \
      "Compatibility alias for the canonical \`$canonical_name\` skill." \
      "$tools_file" \
      "$body_file"
    sync_file "$alias_file" "$REPO_PATH/.claude/skills/$alias_name/SKILL.md" "Synced Claude skill"
  done < <(jq -c '.claude_aliases[]?' <<<"$skill_json")

  if [[ "$export_plugin" == "true" ]]; then
    register_plugin_dir "$canonical_name"
    plugin_file="$tmpdir/${canonical_name}.plugin"
    render_skill \
      "$plugin_file" \
      "$canonical_name" \
      "$canonical_description" \
      "$canonical_name" \
      "$canonical_path" \
      "" \
      "$tools_file" \
      "$body_file"
    sync_file "$plugin_file" "$REPO_PATH/plugins/$PLUGIN_ROOT/skills/$canonical_name/SKILL.md" "Synced plugin skill"
  elif [[ "$export_plugin" != "false" ]]; then
    hg_die "export_plugin must be true or false for $canonical_name"
  fi
done < <(jq -c '.skills[]' "$MANIFEST")

purge_skill_dirs "$REPO_PATH/.claude/skills" "Claude skill" desired_claude_dirs "$CLAUDE_MANAGED"
purge_skill_dirs "$REPO_PATH/plugins/$PLUGIN_ROOT/skills" "plugin skill" desired_plugin_dirs "$PLUGIN_MANAGED"

if [[ "$SKILLS_REF_AVAILABLE" -eq 0 ]]; then
  hg_warn "skills-ref not found; skipped canonical skill validation"
fi

case "$MODE" in
  write)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "$REPO_NAME: skill surface already synchronized"
    fi
    ;;
  dry-run)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "$REPO_NAME: no skill surface changes needed"
    fi
    ;;
  check)
    if [[ "$pending_changes" -eq 0 ]]; then
      hg_ok "$REPO_NAME: skill surface is up to date"
    else
      exit 1
    fi
    ;;
esac
