# Generated by render-palette.sh — do not edit by hand.
# FZF color options — sourced from zsh/zshrc via `source ~/.config/fzf/hg-colors.sh`
# Source: theme/palette.env

export FZF_DEFAULT_OPTS="\
  --color=bg+:#${THEME_SURFACE_ALT},bg:#${THEME_BG},spinner:#${THEME_SECONDARY},hl:#${THEME_PRIMARY} \
  --color=fg:#${THEME_FG},header:#${THEME_MUTED},info:#${THEME_WARNING},pointer:#${THEME_SECONDARY} \
  --color=marker:#${THEME_TERTIARY},fg+:#${THEME_FG},prompt:#${THEME_PRIMARY},hl+:#${THEME_SECONDARY} \
  --color=border:#${THEME_BORDER},separator:#${THEME_BORDER_STRONG},scrollbar:#${THEME_BORDER_STRONG} \
"
